### PR TITLE
update v14 fix

### PR DESCRIPTION
**Pull request by Nrtyck**

### CODE REVIEW

**Comment by kid1194** [comment]
@Nrtyck Thanks a lot for your contribution..

Please check my comments on the changes you made..
And also please explain why you added the v14 files..

**Comment by Nrtyck** [comment]
@kid1194  Frappe v14 install the app, It don't work in edge browser. The contribution fix and test it.

**Comment by kid1194** [comment]
@Nrtyck Thank you bro..
Have you test the plugin  in other browsers, using your fix?

**Review by kid1194 — COMMENTED** [review]
I have made some changes to your repo, if my changes work on edge and other browsers please let me know so I remove the v14 js files you created and merge this pull..

**Comment by Nrtyck** [comment]
It is nice,  I am not sure about the frappe v13 Attach Image control code and fileupdata code. So I'll keep the V13 original code

**Comment by Nrtyck** [comment]
I found that the control code does not work properly in webfrom,I'm trying to fix it, but there are still some problems

**Comment by kid1194** [comment]
@Nrtyck Can you please explain the problem with webform? Maybe I will be able to fix it..

**Comment by Nrtyck** [comment]
at apps/frappe/frappe/public/js/frappe/web_form/webform_script.js 
 function setup_fields(web_form_doc, doc_data) 

here:
		if (["Attach", "Attach Image"].includes(df.fieldtype)) {
				if (typeof df.options !== "object") {
					df.options = {}; // here options to empty
				}
				df.options.disable_file_browser = true;
			}

**Comment by kid1194** [comment]
@Nrtyck For the web form, I think that is not possible to solve the problem..

**Comment by kid1194** [comment]
@Nrtyck I have updated the plugin. I have made a lot of changes in terms of the code.. 
I hope that it works without any problem..

Regarding the web form, I couldn't find a solution..

**Pull request closed without merging**
